### ISSUE TITLE
Refactor how config and certificates are being read

### ISSUE THREAD

**Issue by cebilon123** [cebilon123/waffle#15]
### Context
Currently the config and the certificates are embedded in the `main.go`.  It is good approach for now but it would be nice  to refactor it, in order to make it simpler to set up and edit during the development. 

### TODO
- [ ] Refactor how the config and certificates are being read
- [ ] Add unit tests for the changes
- [ ] Fix other tests accordingly (if it's needed)

### AC
- There is a new approach of reading the configs and certificates
- There are unit tests made for the changes and others are fixed

### How to test?
- The pipeline should succeed
- Unit tests should pass
- WAF should read configs and certificates

**Comment by wrik0** [comment]
@cebilon123 I'm picking this up. I'm assuming you'd like the options for a .env file use as well as a load from os environment as well. I'd like to add validation for certs, the PEM keys during the initial load itself rather than the invocation during proxy.Server.Start(). LMK if you approve.

**Comment by cebilon123** [comment]
Go on. This needs a love, great idea with the validation and env reading. I was thinking about scaling it up, and the kubernates would be a way to go, but this needs to be researched more.
